// sql/oracle/cita.sql.js
module.exports = {
  INSERT: `INSERT INTO CITAS (ID_CITA, ID_PERSONA, FECHA_HORA, MOTIVO) VALUES (:1, :2, :3, :4)`,
  SELECT_ALL: `SELECT * FROM CITAS`,
  SELECT_BY_ID: `SELECT * FROM CITAS WHERE ID_CITA = :1`,
  SELECT_NEXT_24H: `
    SELECT * FROM CITAS 
    WHERE FECHA_HORA BETWEEN SYSDATE AND SYSDATE + 1
  `,
  UPDATE: `UPDATE CITAS SET ID_PERSONA = :2, FECHA_HORA = :3, MOTIVO = :4 WHERE ID_CITA = :1`,
  DELETE: `DELETE FROM CITAS WHERE ID_CITA = :1`
};

