// sql/oracle/persona.sql.js
module.exports = {
  INSERT: `INSERT INTO PERSONAS (ID_PERSONA, NOMBRE, EMAIL, TELEFONO) VALUES (:1, :2, :3, :4)`,
  SELECT_ALL: `SELECT * FROM PERSONAS`,
  SELECT_BY_ID: `SELECT * FROM PERSONAS WHERE ID_PERSONA = :1`,
  UPDATE: `UPDATE PERSONAS SET NOMBRE = :2, EMAIL = :3, TELEFONO = :4 WHERE ID_PERSONA = :1`,
  DELETE: `DELETE FROM PERSONAS WHERE ID_PERSONA = :1`
};
