module.exports = {
  INSERT: `INSERT INTO AVISOS (ID_AVISO, ID_PERSONA, ID_CITA, MENSAJE, FECHA_AVISO) VALUES ($1, $2, $3, $4, $5)`,
  SELECT_ALL: `SELECT * FROM AVISOS`,
  SELECT_BY_PERSONA: 'SELECT * FROM AVISOS WHERE ID_PERSONA = $1',
  SELECT_BY_PERSONA_CITA_MENSAJE_POSTGRES: `SELECT * FROM AVISOS WHERE ID_PERSONA = $1 AND ID_CITA = $2 AND MENSAJE = $3`
};
